/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AuctionBid = IDL.Record({
  'limitExceedingAmount' : IDL.Opt(IDL.Nat),
  'playerName' : IDL.Text,
  'amount' : IDL.Nat,
  'bidderName' : IDL.Text,
});
export const PlayerState = IDL.Record({
  'boughtBy' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'price' : IDL.Opt(IDL.Nat),
});
export const BidderState = IDL.Record({
  'remainingAmount' : IDL.Nat,
  'name' : IDL.Text,
  'isPlaying' : IDL.Bool,
});
export const AuctionState = IDL.Record({
  'roundStartTime' : IDL.Int,
  'highestBidder' : IDL.Opt(IDL.Text),
  'currentAuctionedPlayer' : IDL.Opt(IDL.Text),
  'highestBid' : IDL.Nat,
  'players' : IDL.Vec(PlayerState),
  'bidders' : IDL.Vec(BidderState),
  'inProgress' : IDL.Bool,
  'winners' : IDL.Vec(PlayerState),
});
export const RoundBidResult = IDL.Record({
  'bid' : AuctionBid,
  'state' : AuctionState,
});
export const AudienceLimit = IDL.Record({
  'status' : IDL.Text,
  'maxCapacity' : IDL.Nat,
  'currentCount' : IDL.Nat,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  'bidPlayer' : IDL.Func([AuctionBid, IDL.Text], [RoundBidResult], []),
  'checkAudienceCapacity' : IDL.Func([], [AudienceLimit], ['query']),
  'getAuctionState' : IDL.Func([], [AuctionState], ['query']),
  'joinAudience' : IDL.Func([], [IDL.Bool], []),
  'leaveAudience' : IDL.Func([], [IDL.Bool], []),
  'sellPlayer' : IDL.Func([IDL.Text], [AuctionState], []),
  'startAuction' : IDL.Func([IDL.Text], [AuctionState], []),
  'startNewAuctionWithSecretKey' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
      [AuctionState],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AuctionBid = IDL.Record({
    'limitExceedingAmount' : IDL.Opt(IDL.Nat),
    'playerName' : IDL.Text,
    'amount' : IDL.Nat,
    'bidderName' : IDL.Text,
  });
  const PlayerState = IDL.Record({
    'boughtBy' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'price' : IDL.Opt(IDL.Nat),
  });
  const BidderState = IDL.Record({
    'remainingAmount' : IDL.Nat,
    'name' : IDL.Text,
    'isPlaying' : IDL.Bool,
  });
  const AuctionState = IDL.Record({
    'roundStartTime' : IDL.Int,
    'highestBidder' : IDL.Opt(IDL.Text),
    'currentAuctionedPlayer' : IDL.Opt(IDL.Text),
    'highestBid' : IDL.Nat,
    'players' : IDL.Vec(PlayerState),
    'bidders' : IDL.Vec(BidderState),
    'inProgress' : IDL.Bool,
    'winners' : IDL.Vec(PlayerState),
  });
  const RoundBidResult = IDL.Record({
    'bid' : AuctionBid,
    'state' : AuctionState,
  });
  const AudienceLimit = IDL.Record({
    'status' : IDL.Text,
    'maxCapacity' : IDL.Nat,
    'currentCount' : IDL.Nat,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    'bidPlayer' : IDL.Func([AuctionBid, IDL.Text], [RoundBidResult], []),
    'checkAudienceCapacity' : IDL.Func([], [AudienceLimit], ['query']),
    'getAuctionState' : IDL.Func([], [AuctionState], ['query']),
    'joinAudience' : IDL.Func([], [IDL.Bool], []),
    'leaveAudience' : IDL.Func([], [IDL.Bool], []),
    'sellPlayer' : IDL.Func([IDL.Text], [AuctionState], []),
    'startAuction' : IDL.Func([IDL.Text], [AuctionState], []),
    'startNewAuctionWithSecretKey' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
        [AuctionState],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };