/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AuctionBid {
  'limitExceedingAmount' : [] | [bigint],
  'playerName' : string,
  'amount' : bigint,
  'bidderName' : string,
}
export interface AuctionState {
  'roundStartTime' : bigint,
  'highestBidder' : [] | [string],
  'currentAuctionedPlayer' : [] | [string],
  'highestBid' : bigint,
  'players' : Array<PlayerState>,
  'bidders' : Array<BidderState>,
  'inProgress' : boolean,
  'winners' : Array<PlayerState>,
}
export interface BidderState {
  'remainingAmount' : bigint,
  'name' : string,
  'isPlaying' : boolean,
}
export interface PlayerState {
  'boughtBy' : [] | [string],
  'name' : string,
  'price' : [] | [bigint],
}
export interface RoundBidResult { 'bid' : AuctionBid, 'state' : AuctionState }
export interface _SERVICE {
  'bidPlayer' : ActorMethod<[AuctionBid], RoundBidResult>,
  'getAuctionState' : ActorMethod<[], AuctionState>,
  'sellPlayer' : ActorMethod<[string], AuctionState>,
  'startAuction' : ActorMethod<[string], AuctionState>,
  'startNewAuction' : ActorMethod<
    [string, string, Array<string>],
    AuctionState
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];