/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BidderState {
    remainingAmount: bigint;
    name: string;
    isPlaying: boolean;
}
export interface RoundBidResult {
    bid: AuctionBid;
    state: AuctionState;
}
export interface AuctionState {
    roundStartTime: bigint;
    highestBidder?: string;
    currentAuctionedPlayer?: string;
    highestBid: bigint;
    players: Array<PlayerState>;
    bidders: Array<BidderState>;
    inProgress: boolean;
    winners: Array<PlayerState>;
}
export interface AuctionBid {
    limitExceedingAmount?: bigint;
    playerName: string;
    amount: bigint;
    bidderName: string;
}
export interface PlayerState {
    boughtBy?: string;
    name: string;
    price?: bigint;
}
export interface backendInterface {
    bidPlayer(bid: AuctionBid): Promise<RoundBidResult>;
    getAuctionState(): Promise<AuctionState>;
    sellPlayer(_playerName: string): Promise<AuctionState>;
    startAuction(_playerName: string): Promise<AuctionState>;
    startNewAuction(bidder1Name: string, bidder2Name: string, playerNames: Array<string>): Promise<AuctionState>;
}
import type { AuctionBid as _AuctionBid, AuctionState as _AuctionState, BidderState as _BidderState, PlayerState as _PlayerState, RoundBidResult as _RoundBidResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async bidPlayer(arg0: AuctionBid): Promise<RoundBidResult> {
        if (this.processError) {
            try {
                const result = await this.actor.bidPlayer(to_candid_AuctionBid_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_RoundBidResult_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bidPlayer(to_candid_AuctionBid_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_RoundBidResult_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAuctionState(): Promise<AuctionState> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuctionState();
                return from_candid_AuctionState_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuctionState();
            return from_candid_AuctionState_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async sellPlayer(arg0: string): Promise<AuctionState> {
        if (this.processError) {
            try {
                const result = await this.actor.sellPlayer(arg0);
                return from_candid_AuctionState_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sellPlayer(arg0);
            return from_candid_AuctionState_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async startAuction(arg0: string): Promise<AuctionState> {
        if (this.processError) {
            try {
                const result = await this.actor.startAuction(arg0);
                return from_candid_AuctionState_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startAuction(arg0);
            return from_candid_AuctionState_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async startNewAuction(arg0: string, arg1: string, arg2: Array<string>): Promise<AuctionState> {
        if (this.processError) {
            try {
                const result = await this.actor.startNewAuction(arg0, arg1, arg2);
                return from_candid_AuctionState_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startNewAuction(arg0, arg1, arg2);
            return from_candid_AuctionState_n8(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AuctionBid_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuctionBid): AuctionBid {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_AuctionState_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuctionState): AuctionState {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_PlayerState_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerState): PlayerState {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_RoundBidResult_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoundBidResult): RoundBidResult {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    boughtBy: [] | [string];
    name: string;
    price: [] | [bigint];
}): {
    boughtBy?: string;
    name: string;
    price?: bigint;
} {
    return {
        boughtBy: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.boughtBy)),
        name: value.name,
        price: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.price))
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bid: _AuctionBid;
    state: _AuctionState;
}): {
    bid: AuctionBid;
    state: AuctionState;
} {
    return {
        bid: from_candid_AuctionBid_n5(_uploadFile, _downloadFile, value.bid),
        state: from_candid_AuctionState_n8(_uploadFile, _downloadFile, value.state)
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    limitExceedingAmount: [] | [bigint];
    playerName: string;
    amount: bigint;
    bidderName: string;
}): {
    limitExceedingAmount?: bigint;
    playerName: string;
    amount: bigint;
    bidderName: string;
} {
    return {
        limitExceedingAmount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.limitExceedingAmount)),
        playerName: value.playerName,
        amount: value.amount,
        bidderName: value.bidderName
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    roundStartTime: bigint;
    highestBidder: [] | [string];
    currentAuctionedPlayer: [] | [string];
    highestBid: bigint;
    players: Array<_PlayerState>;
    bidders: Array<_BidderState>;
    inProgress: boolean;
    winners: Array<_PlayerState>;
}): {
    roundStartTime: bigint;
    highestBidder?: string;
    currentAuctionedPlayer?: string;
    highestBid: bigint;
    players: Array<PlayerState>;
    bidders: Array<BidderState>;
    inProgress: boolean;
    winners: Array<PlayerState>;
} {
    return {
        roundStartTime: value.roundStartTime,
        highestBidder: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.highestBidder)),
        currentAuctionedPlayer: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.currentAuctionedPlayer)),
        highestBid: value.highestBid,
        players: from_candid_vec_n11(_uploadFile, _downloadFile, value.players),
        bidders: value.bidders,
        inProgress: value.inProgress,
        winners: from_candid_vec_n11(_uploadFile, _downloadFile, value.winners)
    };
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PlayerState>): Array<PlayerState> {
    return value.map((x)=>from_candid_PlayerState_n12(_uploadFile, _downloadFile, x));
}
function to_candid_AuctionBid_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AuctionBid): _AuctionBid {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    limitExceedingAmount?: bigint;
    playerName: string;
    amount: bigint;
    bidderName: string;
}): {
    limitExceedingAmount: [] | [bigint];
    playerName: string;
    amount: bigint;
    bidderName: string;
} {
    return {
        limitExceedingAmount: value.limitExceedingAmount ? candid_some(value.limitExceedingAmount) : candid_none(),
        playerName: value.playerName,
        amount: value.amount,
        bidderName: value.bidderName
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
